services:
  web:
    build:
      context: .
    image: moonfished-backend:${TAG:-dev}
    env_file:
      - ${ENV_FILE:-.env.development}
    ports:
      - "8000:8000"
    depends_on:
      - db
    command: >
      sh -c "
        if [ \"$DJANGO_ENV\" = \"production\" ]; then
          python manage.py migrate &&
          python manage.py collectstatic --noinput &&
          python manage.py runserver 0.0.0.0:8000;
        else
          python manage.py runserver 0.0.0.0:8000;
        fi
      "
    volumes:
      - .:/app

  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - ${ENV_FILE:-.env.development}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
